### ISSUE TITLE
Make product listing info inaccessible to users who are not logged in.

### ISSUE THREAD

**Issue by Jargon4072** [TheCaffeineDev/Real-Estate-Django-Web-App#7]
Hi,
I want to make the product listing inaccessible to users who are not logged in. How to do that?

**Comment by TheCaffeineDev** [comment]
Hi, @Jargon4072  If you want to show the products to the logged in users only then there are two things. If products have a foreign key to the user, then as easy as:

`listings = Product.objects.filter(user=request.user)`

or you can simply add an if-else code snippet in Django app views like if the user is authenticated then only show the product listing otherwise show another page.

**Comment by Jargon4072** [comment]
> Hi, @Jargon4072 If you want to show the products to the logged in users only then there are two things. If products have a foreign key to the user, then as easy as:
> 
> `listings = Product.objects.filter(user=request.user)`
> 
> or you can simply add an if-else code snippet in Django app views like if the user is authenticated then only show the product listing otherwise show another page.

Thanks, simple if-else worked for me!
